seed_everything: 5318008
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: gaitgraph-oumvlp-{epoch:02d}-{val_loss_epoch:.2f}
      monitor: val_loss_epoch
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      every_n_val_epochs: null
  - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
    init_args:
      swa_epoch_start: 0.8
      swa_lrs: null
      annealing_epochs: 10
      annealing_strategy: cos
      device: cuda
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: 1,
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 10
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 750
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 25
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  learning_rate: 0.005
  lr_div_factor: 25.0
  loss_temperature: 0.01
  embedding_layer_size: 128
  multi_input: true
  backend_name: resgcn-n51-r4
  tta: true
data:
  data_path: ../data
  dataset_path: ../../datasets/OUMVLP-Pose
  keypoints: alphapose
  batch_size: 768
  num_workers: 8
  sequence_length: 30
  multi_input: true
  flip_sequence_p: 0.5
  flip_lr_p: 0.5
  joint_noise: 0.5
  point_noise: 0.05
  confidence_noise: 0.01
  random_move: 3.0
ckpt_path: null
